version: "3"
services:
  application:
    image: myreport
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - maildev
    depends_on:
      - maildev
    volumes:
      - ./src:/app/
    ports:
      - "9090:80"
  maildev:
    restart: always
    image: djfarrelly/maildev
    ports:
      - "1087:80"
