
-- Définition des PDV

INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00001" ,LIE_NOM="PDV 1" ,LIE_ADR1="1 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Ville" ,LIE_TYPO2="Oui" ,LIE_TYPO3="0 - 150" ,LIE_TYPO4="0 - 500" ,LIE_TYPO5="oui" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00002" ,LIE_NOM="PDV 2" ,LIE_ADR1="2 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Ville" ,LIE_TYPO2="Oui" ,LIE_TYPO3="0 - 150" ,LIE_TYPO4="0 - 500" ,LIE_TYPO5="oui" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00003" ,LIE_NOM="PDV 3" ,LIE_ADR1="3 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Ville" ,LIE_TYPO2="Oui" ,LIE_TYPO3="0 - 150" ,LIE_TYPO4="0 - 500" ,LIE_TYPO5="oui" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00004" ,LIE_NOM="PDV 4" ,LIE_ADR1="4 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Ville" ,LIE_TYPO2="Oui" ,LIE_TYPO3="0 - 150" ,LIE_TYPO4="0 - 500" ,LIE_TYPO5="oui" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00005" ,LIE_NOM="PDV 5" ,LIE_ADR1="5 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Ville" ,LIE_TYPO2="Oui" ,LIE_TYPO3="0 - 150" ,LIE_TYPO4="0 - 500" ,LIE_TYPO5="oui" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00006" ,LIE_NOM="PDV 6" ,LIE_ADR1="6 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Ville" ,LIE_TYPO2="Oui" ,LIE_TYPO3="0 - 150" ,LIE_TYPO4="0 - 500" ,LIE_TYPO5="oui" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00007" ,LIE_NOM="PDV 7" ,LIE_ADR1="7 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Ville" ,LIE_TYPO2="Oui" ,LIE_TYPO3="0 - 150" ,LIE_TYPO4="0 - 500" ,LIE_TYPO5="oui" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00008" ,LIE_NOM="PDV 8" ,LIE_ADR1="8 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Ville" ,LIE_TYPO2="Oui" ,LIE_TYPO3="0 - 150" ,LIE_TYPO4="500 - 800" ,LIE_TYPO5="oui" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00009" ,LIE_NOM="PDV 9" ,LIE_ADR1="9 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Ville" ,LIE_TYPO2="Oui" ,LIE_TYPO3="0 - 150" ,LIE_TYPO4="500 - 800" ,LIE_TYPO5="oui" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00010" ,LIE_NOM="PDV 10" ,LIE_ADR1="10 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Ville" ,LIE_TYPO2="Oui" ,LIE_TYPO3="0 - 150" ,LIE_TYPO4="500 - 800" ,LIE_TYPO5="oui" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00011" ,LIE_NOM="PDV 11" ,LIE_ADR1="11 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Autoroute" ,LIE_TYPO2="Oui" ,LIE_TYPO3="150 - 300" ,LIE_TYPO4="500 - 800" ,LIE_TYPO5="oui" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00012" ,LIE_NOM="PDV 12" ,LIE_ADR1="12 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Autoroute" ,LIE_TYPO2="Oui" ,LIE_TYPO3="150 - 300" ,LIE_TYPO4="500 - 800" ,LIE_TYPO5="oui" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00013" ,LIE_NOM="PDV 13" ,LIE_ADR1="13 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Autoroute" ,LIE_TYPO2="Oui" ,LIE_TYPO3="150 - 300" ,LIE_TYPO4="500 - 800" ,LIE_TYPO5="oui" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00014" ,LIE_NOM="PDV 14" ,LIE_ADR1="14 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Autoroute" ,LIE_TYPO2="Oui" ,LIE_TYPO3="150 - 300" ,LIE_TYPO4="500 - 800" ,LIE_TYPO5="oui" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00015" ,LIE_NOM="PDV 15" ,LIE_ADR1="15 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Autoroute" ,LIE_TYPO2="Oui" ,LIE_TYPO3="150 - 300" ,LIE_TYPO4="500 - 800" ,LIE_TYPO5="oui" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00016" ,LIE_NOM="PDV 16" ,LIE_ADR1="16 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Autoroute" ,LIE_TYPO2="Non" ,LIE_TYPO3="150 - 300" ,LIE_TYPO4="800 - 1100" ,LIE_TYPO5="non" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00017" ,LIE_NOM="PDV 17" ,LIE_ADR1="17 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Autoroute" ,LIE_TYPO2="Non" ,LIE_TYPO3="150 - 300" ,LIE_TYPO4="800 - 1100" ,LIE_TYPO5="non" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00018" ,LIE_NOM="PDV 18" ,LIE_ADR1="18 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Autoroute" ,LIE_TYPO2="Non" ,LIE_TYPO3="150 - 300" ,LIE_TYPO4="800 - 1100" ,LIE_TYPO5="non" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00019" ,LIE_NOM="PDV 19" ,LIE_ADR1="19 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Autoroute" ,LIE_TYPO2="Non" ,LIE_TYPO3="150 - 300" ,LIE_TYPO4="800 - 1100" ,LIE_TYPO5="non" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00020" ,LIE_NOM="PDV 20" ,LIE_ADR1="20 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Autoroute" ,LIE_TYPO2="Non" ,LIE_TYPO3="150 - 300" ,LIE_TYPO4="800 - 1100" ,LIE_TYPO5="non" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00021" ,LIE_NOM="PDV 21" ,LIE_ADR1="21 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Campagne" ,LIE_TYPO2="Non" ,LIE_TYPO3="+ de 300" ,LIE_TYPO4="800 - 1100" ,LIE_TYPO5="non" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00022" ,LIE_NOM="PDV 22" ,LIE_ADR1="22 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Campagne" ,LIE_TYPO2="Non" ,LIE_TYPO3="+ de 300" ,LIE_TYPO4="800 - 1100" ,LIE_TYPO5="non" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00023" ,LIE_NOM="PDV 23" ,LIE_ADR1="23 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Campagne" ,LIE_TYPO2="Non" ,LIE_TYPO3="+ de 300" ,LIE_TYPO4="+ de 1100" ,LIE_TYPO5="non" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00024" ,LIE_NOM="PDV 24" ,LIE_ADR1="24 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Campagne" ,LIE_TYPO2="Non" ,LIE_TYPO3="+ de 300" ,LIE_TYPO4="+ de 1100" ,LIE_TYPO5="non" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00025" ,LIE_NOM="PDV 25" ,LIE_ADR1="25 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Campagne" ,LIE_TYPO2="Non" ,LIE_TYPO3="+ de 300" ,LIE_TYPO4="+ de 1100" ,LIE_TYPO5="non" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00026" ,LIE_NOM="PDV 26" ,LIE_ADR1="26 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Campagne" ,LIE_TYPO2="Non" ,LIE_TYPO3="+ de 300" ,LIE_TYPO4="+ de 1100" ,LIE_TYPO5="non" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00027" ,LIE_NOM="PDV 27" ,LIE_ADR1="27 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Campagne" ,LIE_TYPO2="Non" ,LIE_TYPO3="+ de 300" ,LIE_TYPO4="+ de 1100" ,LIE_TYPO5="non" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00028" ,LIE_NOM="PDV 28" ,LIE_ADR1="28 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Campagne" ,LIE_TYPO2="Non" ,LIE_TYPO3="+ de 300" ,LIE_TYPO4="+ de 1100" ,LIE_TYPO5="non" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00029" ,LIE_NOM="PDV 29" ,LIE_ADR1="29 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Campagne" ,LIE_TYPO2="Non" ,LIE_TYPO3="+ de 300" ,LIE_TYPO4="+ de 1100" ,LIE_TYPO5="non" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
INSERT INTO lieu SET LIE_ACTIVE="oui" ,LIE_CODE="00030" ,LIE_NOM="PDV 30" ,LIE_ADR1="30 rue de la démo" ,LIE_ADR2="" ,LIE_CP="14000" ,LIE_VILLE="Caen" ,LIE_TEL="" ,codeChefRegion="1" ,codeChefSecteur="1" ,LIE_TYPO1="Campagne" ,LIE_TYPO2="Non" ,LIE_TYPO3="+ de 300" ,LIE_TYPO4="+ de 1100" ,LIE_TYPO5="non" ,LIE_NUM="" ,LIE_LUB="" ,LIE_CARB="" ,LIE_GPLC="" ,LIE_SDEB="" ,LIE_SFIN="";
