
-- Attribution des comptables sur les SARL

INSERT INTO stationcc SET STA_NUM=1, CC_NUM=1;
INSERT INTO stationcc SET STA_NUM=2, CC_NUM=2;
INSERT INTO stationcc SET STA_NUM=3, CC_NUM=3;
INSERT INTO stationcc SET STA_NUM=4, CC_NUM=4;
INSERT INTO stationcc SET STA_NUM=5, CC_NUM=5;
INSERT INTO stationcc SET STA_NUM=6, CC_NUM=6;
INSERT INTO stationcc SET STA_NUM=7, CC_NUM=7;
INSERT INTO stationcc SET STA_NUM=8, CC_NUM=8;
INSERT INTO stationcc SET STA_NUM=9, CC_NUM=9;
INSERT INTO stationcc SET STA_NUM=10, CC_NUM=10;
INSERT INTO stationcc SET STA_NUM=11, CC_NUM=11;
INSERT INTO stationcc SET STA_NUM=12, CC_NUM=12;
INSERT INTO stationcc SET STA_NUM=13, CC_NUM=13;
INSERT INTO stationcc SET STA_NUM=14, CC_NUM=14;
INSERT INTO stationcc SET STA_NUM=15, CC_NUM=15;
INSERT INTO stationcc SET STA_NUM=16, CC_NUM=16;
INSERT INTO stationcc SET STA_NUM=17, CC_NUM=17;
INSERT INTO stationcc SET STA_NUM=18, CC_NUM=18;
INSERT INTO stationcc SET STA_NUM=19, CC_NUM=19;
INSERT INTO stationcc SET STA_NUM=20, CC_NUM=20;
INSERT INTO stationcc SET STA_NUM=21, CC_NUM=21;
INSERT INTO stationcc SET STA_NUM=22, CC_NUM=22;
INSERT INTO stationcc SET STA_NUM=23, CC_NUM=23;
INSERT INTO stationcc SET STA_NUM=24, CC_NUM=24;
INSERT INTO stationcc SET STA_NUM=25, CC_NUM=25;
INSERT INTO stationcc SET STA_NUM=26, CC_NUM=26;
INSERT INTO stationcc SET STA_NUM=27, CC_NUM=27;
INSERT INTO stationcc SET STA_NUM=28, CC_NUM=28;
INSERT INTO stationcc SET STA_NUM=29, CC_NUM=29;
INSERT INTO stationcc SET STA_NUM=30, CC_NUM=30;